name: alphabet_slider
description: A Flutter plugin for an Alphabet slider.
version: 1.0.0
repository: https://github.com/sabarinath-m/alphabet_slider

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
