name: alphabet_slider
description: A Flutter plugin for an Alphabet slider, commonly used in phone contact listing pages. This package provides a widget that lists all the alphabets vertically. Users can select an alphabet by either sliding on top of the list or clicking on an alphabet. Also we can pass fontSize, textColor, selectedTextColor onLetterSelect callback to the widget. Use this widget with a Stack widget and align based on your UI requirement.
version: 1.0.1
repository: https://github.com/sabarinath-m/alphabet_slider.git

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
