name: alphabet_slider
description: A Flutter plugin for an Alphabet slider, commonly used in phone contact listing pages.
version: 1.0.5
repository: https://github.com/sabarinath-m/alphabet_slider.git

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
