name: Publish package
run-name: Publish package ${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      versionToUpdate:
        required: true
        description: Choose version to update
        type: choice
        options:
          - "Major"
          - "Minor"
          - "Patch"
jobs:
  update-version-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
         export BRANCH=${{ steps.branch-names.outputs.current_branch }}
         echo "branch: $BRANCH"
         if [[ "$BRANCH" != "main" ]]; then
          echo "Tagging cannot be done on branch other than main"
          echo $BRANCH
          exit 1
         fi
         export VERSION=$(cat pubspec.yaml | grep "version:" | awk '{print $2}' | sed 's/^[ \t]*//;s/[ \t]*$//')
         echo $VERSION
         export UPDATE_CHOICE = ${{ github.event.inputs.versionToUpdate }}
         export MAJOR=$(echo $VERSION | cut -d. -f1)
         export MINOR=$(echo $VERSION | cut -d. -f2)
         export PATCH=$(echo $VERSION | cut -d"+" -f1 | cut -d"." -f3)
         export BUILD_NUMBER=$(echo $VERSION | cut -d"+" -f2)
         export NEW_BUILD_NUMBER=$(($BUILD_NUMBER + 1))
         if [[ "$UPDATE_CHOICE" == "Major" ]]; then export NEW_TAG=$((MAJOR + 1)).0.0+$NEW_BUILD_NUMBER; fi
         if [[ "$UPDATE_CHOICE" == "Minor" ]]; then export NEW_TAG=$MAJOR.$((MINOR + 1)).0+$NEW_BUILD_NUMBER; fi
         if [[ "$UPDATE_CHOICE" == "Patch" ]]; then export NEW_TAG=$MAJOR.$MINOR.$((PATCH + 1))+$NEW_BUILD_NUMBER; fi
         sed -i "s/version: $VERSION/version: $NEW_TAG/g" pubspec.yaml
         git add pubspec.yaml
         git commit -m "Version bumped to $NEW_TAG"
         git tag $NEW_TAG
         git push --tags
         git push origin $BRANCH

         
          
